spring.application.name=github-entrega-inicial
spring.datasource.url=jdbc:postgresql://localhost:5432/db_compras
spring.datasource.username=postgres
spring.datasource.password=sopa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true